import nodemailer from 'nodemailer';

interface EmailOptions {
  to: string;
  subject: string;
  message: string;
  reportBuffer: Buffer;
  reportFileName: string;
}

class EmailService {
  private transporter: nodemailer.Transporter;

  constructor() {
    // Configure for Outlook/Office 365
    this.transporter = nodemailer.createTransporter({
      host: 'smtp-mail.outlook.com',
      port: 587,
      secure: false,
      auth: {
        user: process.env.EMAIL_USER || '', // Will need to be configured
        pass: process.env.EMAIL_PASSWORD || '' // Will need to be configured
      }
    });
  }

  async sendReportEmail(options: EmailOptions): Promise<void> {
    try {
      const mailOptions = {
        from: process.env.EMAIL_USER || 'noreply@wrenchd.com',
        to: options.to,
        subject: options.subject,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: #22c55e; color: white; padding: 20px; text-align: center;">
              <h1>Wrench'd IVHC</h1>
              <p>Professional Vehicle Health Check Report</p>
            </div>
            
            <div style="padding: 20px; background: #f9fafb;">
              <h2 style="color: #1f2937;">Your Vehicle Health Check Report</h2>
              <p style="color: #6b7280; line-height: 1.6;">
                ${options.message}
              </p>
              
              <div style="margin: 20px 0; padding: 15px; background: white; border-left: 4px solid #22c55e;">
                <p style="margin: 0; color: #374151;">
                  <strong>Report attached:</strong> ${options.reportFileName}
                </p>
              </div>
              
              <div style="margin: 30px 0; text-align: center;">
                <div style="background: #22c55e; color: white; padding: 15px; border-radius: 8px; display: inline-block;">
                  <strong>Preece Auto Repairs</strong><br>
                  Suspension • Servicing • Tyres
                </div>
              </div>
            </div>
            
            <div style="background: #1f2937; color: white; padding: 15px; text-align: center; font-size: 12px;">
              <p>This report was generated by Wrench'd IVHC Professional Vehicle Health Check System</p>
              <p>© ${new Date().getFullYear()} Preece Auto Repairs. All rights reserved.</p>
            </div>
          </div>
        `,
        attachments: [
          {
            filename: options.reportFileName,
            content: options.reportBuffer,
            contentType: 'application/pdf'
          }
        ]
      };

      await this.transporter.sendMail(mailOptions);
      console.log('Report email sent successfully to:', options.to);
    } catch (error) {
      console.error('Error sending email:', error);
      throw new Error('Failed to send email');
    }
  }

  async testConnection(): Promise<boolean> {
    try {
      await this.transporter.verify();
      return true;
    } catch (error) {
      console.error('Email connection test failed:', error);
      return false;
    }
  }
}

export const emailService = new EmailService();